---
    - name: "Deploiement de Postgres"
      docker_container:
            name: "{{ postgresql_container_name }}"
            image: postgres:9.6-alpine
            state: started
            ports: 5432:5432
            env:
              ENV POSTGRES_PASSWORD: root
            tty: yes
            pull: yes
            networks:
              - name: subnet1
                #ipv4_address: 10.0.0.4
            volumes: "volume_postgres:/var/lib/postgresql"