---
    - name: "Deploiement de Postgres"
      docker_container:
            name: ldhost
            #env_file: /home/formation/autom2/a2projet4/group_vars/mysql.yml
            image: postgres:9.6-alpine
            state: started
            env:
              ENV POSTGRES_PASSWORD: root
            tty: yes
            pull: yes
            hostname: ldhost
            purge_networks: yes
            networks:
              - name: subnet1
                ipv4_address: 10.0.0.4
            volumes: "volume_postgres:/var/lib/postgresql"