---
    - name: "Deploiement de Mysql"
      docker_container:
            name: ldhost
            image: mysql:5.7
            state: started
            ports: 3306:3306
            env:
              MYSQL_ROOT_PASSWORD: root
              MYSQL_ROOT_HOST: '%'
            tty: yes
            pull: yes
            #hostname: ldhost
            networks:
              - name: subnet1
                ipv4_address: 10.0.0.3
            volumes: "volume_mysql:/var/lib/mysql"