---
    - name: "Deploiement de Mysql"
      docker_container:
            name: "{{ mysql_container_name }}"
            image: mysql:5.7
            state: started
            ports: 3306:3306
            env:
              MYSQL_ROOT_PASSWORD: root
              MYSQL_ROOT_HOST: '%'
            tty: yes
            pull: yes
            networks:
              - name: subnet1
                links: "{{ mysql_container_name }}:{{ ldoc_container_name }}"
            volumes: "volume_mysql:/var/lib/mysql"